# -*- coding: utf-8 -*-
"""Final_ResNet_Config_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YfUFFuu26HWKJqzT-0kN5lBbDfhVoeMC

Pre processing code
"""

pip install --upgrade pip

pip install pandas pillow lxml matplotlib torchvision torch tqdm

pip install grad-cam

!pip install pandas pillow lxml matplotlib tqdm torch torchvision --quiet

import os
import glob
import pandas as pd
import xml.etree.ElementTree as ET
from tqdm import tqdm
from PIL import Image
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
import torch
import matplotlib.pyplot as plt

# ==== Set dataset paths ====
BASE_DIR = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/28455641/TN5000_forReview/TN5000_forReview"
ANN_DIR = os.path.join(BASE_DIR, "Annotations")
IMG_DIR = os.path.join(BASE_DIR, "JPEGImages")
SPLIT_DIR = os.path.join(BASE_DIR, "ImageSets", "Main")

print("✅ Dataset folders found:")
print("Annotations:", len(os.listdir(ANN_DIR)), "xml files")
print("Images:", len(os.listdir(IMG_DIR)), "jpg files")
print("Splits:", os.listdir(SPLIT_DIR))

"""# STEP 3: Parse XML Annotations → Create a Master CSV

Each .xml file contains bounding box coordinates and the label (0 = benign, 1 = malignant).
This step reads all XMLs and builds tn5000_annotations.csv.
"""

# parse_voc_xmls_to_csv.py
import os
import glob
import xml.etree.ElementTree as ET
import pandas as pd
from PIL import Image

# -------- CONFIG --------
ANNOTATIONS_DIR = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/28455641/TN5000_forReview/TN5000_forReview/Annotations"
IMAGES_DIR      = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/28455641/TN5000_forReview/TN5000_forReview/JPEGImages"
OUT_CSV         = "tn5000_annotations.csv"
VALIDATE_BBOXES = True   # set False to skip image-size checks
# ------------------------

rows = []
xml_files = sorted(glob.glob(os.path.join(ANNOTATIONS_DIR, "*.xml")))
print(f"Found {len(xml_files)} XML files in {ANNOTATIONS_DIR}")

for xml_path in xml_files:
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
    except Exception as e:
        print(f"Warning: failed to parse {xml_path}: {e}")
        continue

    # filename as given in XML (e.g., 000001.jpg)
    filename_node = root.find("filename")
    if filename_node is None:
        print(f"Warning: no <filename> in {xml_path}, skipping")
        continue
    filename = filename_node.text.strip()

    # image size (if present)
    size_node = root.find("size")
    if size_node is not None:
        try:
            width  = int(size_node.find("width").text)
            height = int(size_node.find("height").text)
            depth  = int(size_node.find("depth").text) if size_node.find("depth") is not None else None
        except Exception:
            width = height = depth = None
    else:
        width = height = depth = None

    # If chosen, try to read actual image to validate sizes
    if VALIDATE_BBOXES:
        img_path = os.path.join(IMAGES_DIR, filename)
        if os.path.exists(img_path):
            try:
                with Image.open(img_path) as im:
                    real_w, real_h = im.size
                # if XML size absent or inconsistent, overwrite with real value
                if width is None or height is None or (width != real_w or height != real_h):
                    width, height = real_w, real_h
            except Exception as e:
                print(f"Warning: cannot open image {img_path}: {e}")

    # iterate objects (one row per object)
    object_nodes = root.findall("object")
    if not object_nodes:
        # If no object, write a row with NaNs for bbox
        rows.append([filename, None, width, height, depth, None, None, None, None, os.path.basename(xml_path)])
        continue

    for obj in object_nodes:
        name_node = obj.find("name")
        label_text = name_node.text.strip() if name_node is not None else None

        # Convert label_text to integer if possible (your XML shows '0'/'1')
        label = None
        if label_text is not None:
            try:
                label = int(label_text)
            except ValueError:
                label = label_text  # leave as string if cannot convert

        bnd = obj.find("bndbox")
        if bnd is None:
            xmin = ymin = xmax = ymax = None
        else:
            try:
                xmin = int(float(bnd.find("xmin").text))
                ymin = int(float(bnd.find("ymin").text))
                xmax = int(float(bnd.find("xmax").text))
                ymax = int(float(bnd.find("ymax").text))
            except Exception:
                xmin = ymin = xmax = ymax = None

        # clamp boxes to image bounds if we know width/height
        if VALIDATE_BBOXES and width is not None and height is not None and xmin is not None:
            xmin = max(0, min(xmin, width-1))
            xmax = max(0, min(xmax, width-1))
            ymin = max(0, min(ymin, height-1))
            ymax = max(0, min(ymax, height-1))

        rows.append([
            filename,           # image filename
            label,              # label (0/1 or string)
            width, height, depth,
            xmin, ymin, xmax, ymax,
            os.path.basename(xml_path)  # source xml file
        ])

# Build DataFrame
cols = ["image","label","img_width","img_height","img_depth","xmin","ymin","xmax","ymax","xml_file"]
df = pd.DataFrame(rows, columns=cols)

# basic sanity checks and reporting
print("\nParsed dataframe shape:", df.shape)
print("Label value counts (first 20):")
print(df['label'].value_counts(dropna=False).head(20))
print("\nSome sample rows:")
print(df.head(8))

# save CSV
df.to_csv(OUT_CSV, index=False)
print(f"\nSaved parsed annotations to {OUT_CSV}")

"""Step 4 exactly as you need it: code + short explanation + sanity checks.
This will read the official train.txt, val.txt, test.txt files from TN5000_forReview/ImageSets/Main/, attach a split column to your tn5000_annotations.csv, validate image presence, and save tn5000_annotations_split.csv.

Run this in the same working directory where TN5000_forReview/ and tn5000_annotations.csv live.

What this step does (brief)
Reads train.txt, val.txt, test.txt (each line is an image id without extension).
Maps each annotation row to train / val / test according to the provided lists.
Flags any images not found in splits as unknown.
Validates that image files exist in JPEGImages/.
Writes tn5000_annotations_split.csv and prints helpful counts.
"""

# step4_add_splits.py
import os
import pandas as pd

# --- Config (adjust if your folders are different) ---
BASE_DIR = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/28455641/TN5000_forReview/TN5000_forReview"
SPLIT_DIR = os.path.join(BASE_DIR, "ImageSets", "Main")
IMG_DIR = os.path.join(BASE_DIR, "JPEGImages")
IN_CSV = "tn5000_annotations.csv"
OUT_CSV = "tn5000_annotations_split.csv"
# -----------------------------------------------------

# 1) load annotations CSV
df = pd.read_csv(IN_CSV)
print(f"Loaded annotations: {len(df)} rows from {IN_CSV}")

# 2) helper to read id lists and append .jpg
def read_ids(path):
    if not os.path.exists(path):
        print(f"Warning: split file not found: {path}")
        return set()
    with open(path, "r") as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    # convert ids to filenames as used in annotations (add .jpg)
    return set([ln + ".jpg" for ln in lines])

train_ids = read_ids(os.path.join(SPLIT_DIR, "train.txt"))
val_ids   = read_ids(os.path.join(SPLIT_DIR, "val.txt"))
test_ids  = read_ids(os.path.join(SPLIT_DIR, "test.txt"))
print(f"Split sizes found — train: {len(train_ids)}, val: {len(val_ids)}, test: {len(test_ids)}")

# 3) map each image -> split
def map_split(img_name):
    if img_name in train_ids: return "train"
    if img_name in val_ids:   return "val"
    if img_name in test_ids:  return "test"
    return "unknown"

df["split"] = df["image"].apply(map_split)

# 4) sanity check: any unknown images?
unknown_count = (df["split"] == "unknown").sum()
if unknown_count > 0:
    print(f"Note: {unknown_count} annotation rows have image not present in train/val/test splits (marked 'unknown').")
    # optional: list a few examples
    print(df[df["split"]=="unknown"]["image"].drop_duplicates().head(10).tolist())

# 5) validate image files exist
missing_images = []
for img in df["image"].unique():
    if not os.path.exists(os.path.join(IMG_DIR, img)):
        missing_images.append(img)
if missing_images:
    print(f"Warning: {len(missing_images)} images referenced in CSV are missing in {IMG_DIR}. Example(s): {missing_images[:5]}")
else:
    print("All referenced images exist in JPEGImages folder.")

# 6) print per-split counts (rows and unique images)
print("\nAnnotation counts by split (rows):")
print(df["split"].value_counts())

print("\nUnique image counts by split:")
print(df.groupby("split")["image"].nunique())

# 7) per-split class balance summary
print("\nPer-split label distribution (label counts):")
for s in ["train","val","test","unknown"]:
    if s in df["split"].values:
        sub = df[df["split"]==s]
        print(f" {s}: {sub['label'].value_counts().to_dict()}  (total rows: {len(sub)})")

# 8) save output CSV
df.to_csv(OUT_CSV, index=False)
print(f"\nSaved updated CSV with splits to: {OUT_CSV}")

!ls -lh /content | grep tn5000

!cp /content/tn5000_annotations_split.csv "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/"

"""Step 5: Cropping script you can run in Colab right now. It reads your tn5000_annotations_split.csv, crops each bounding box from the original images, and saves the cropped nodule patches into organized folders:"""

# Step 5: crop_nodules_and_save.py
import os, pandas as pd
from PIL import Image
from tqdm import tqdm

# ----------------- CONFIG -----------------
# Path in your Drive where you stored CSVs and original JPEGImages folder
DRIVE_PROJECT = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project"
CSV_PATH      = os.path.join(DRIVE_PROJECT, "tn5000_annotations_split.csv")
IMG_DIR       = os.path.join(DRIVE_PROJECT, "28455641", "TN5000_forReview", "TN5000_forReview", "JPEGImages")
OUT_ROOT      = os.path.join(DRIVE_PROJECT, "TN5000_crops")   # output root (will create train/val/test)
# Optional: also save a resized version for quick experiments
SAVE_RESIZED = False
RESIZED_SIZE = (224,224)   # only used if SAVE_RESIZED=True

# If you've copied dataset to local /content for speed, use these instead:
# CSV_PATH = "/content/tn5000_annotations_split.csv"
# IMG_DIR  = "/content/TN5000_local/JPEGImages"
# OUT_ROOT = "/content/TN5000_crops"
# ------------------------------------------

os.makedirs(OUT_ROOT, exist_ok=True)
for s in ["train","val","test","unknown"]:
    os.makedirs(os.path.join(OUT_ROOT, s), exist_ok=True)
    if SAVE_RESIZED:
        os.makedirs(os.path.join(OUT_ROOT, f"{s}_resized"), exist_ok=True)

# ----------------- LOAD CSV -----------------
df = pd.read_csv(CSV_PATH)
print("Total annotation rows:", len(df))
print("Unique images:", df['image'].nunique())
print("Split counts (images):")
print(df.groupby('split')['image'].nunique())

# ----------------- Group by image and crop -----------------
# We'll create unique crop filenames when multiple boxes exist per image
grouped = df.groupby('image')

total_saved = 0
missing_images = []
crop_records = []  # to optionally save a manifest of crops

for img_name, sub in tqdm(grouped, desc="Processing images"):
    img_path = os.path.join(IMG_DIR, img_name)
    if not os.path.exists(img_path):
        missing_images.append(img_name)
        continue
    try:
        with Image.open(img_path) as im:
            im = im.convert("RGB")
            img_w, img_h = im.size
            # iterate objects for this image (preserves the row order)
            for i, (_, row) in enumerate(sub.reset_index(drop=True).iterrows(), start=1):
                xmin = int(row['xmin']) if not pd.isna(row['xmin']) else 0
                ymin = int(row['ymin']) if not pd.isna(row['ymin']) else 0
                xmax = int(row['xmax']) if not pd.isna(row['xmax']) else img_w-1
                ymax = int(row['ymax']) if not pd.isna(row['ymax']) else img_h-1
                # clamp
                xmin = max(0, min(xmin, img_w-1))
                ymin = max(0, min(ymin, img_h-1))
                xmax = max(0, min(xmax, img_w-1))
                ymax = max(0, min(ymax, img_h-1))
                # ensure non-zero box
                if xmax <= xmin or ymax <= ymin:
                    # skip invalid box
                    continue
                crop = im.crop((xmin, ymin, xmax, ymax))
                split = row['split'] if 'split' in row and pd.notna(row['split']) else 'unknown'
                # build unique filename: originalname_idx.jpg (idx for multiple bboxes)
                base, ext = os.path.splitext(img_name)
                out_name = f"{base}_{i}{ext}"
                out_path = os.path.join(OUT_ROOT, split, out_name)
                crop.save(out_path)
                total_saved += 1
                crop_records.append({
                    "orig_image": img_name,
                    "crop_name": out_name,
                    "split": split,
                    "label": row['label'],
                    "xmin": xmin, "ymin": ymin, "xmax": xmax, "ymax": ymax,
                    "out_path": out_path
                })
                # optional resized save
                if SAVE_RESIZED:
                    resized = crop.resize(RESIZED_SIZE, Image.BILINEAR)
                    resized.save(os.path.join(OUT_ROOT, f"{split}_resized", out_name))
    except Exception as e:
        print(f"Warning: failed to process {img_path}: {e}")
        missing_images.append(img_name)

# ----------------- Summary -----------------
print("\nDONE.")
print("Total crops saved:", total_saved)
print("Missing/failed images:", len(missing_images))
if missing_images:
    print("Example missing images:", missing_images[:5])

# Save a small manifest CSV of all crops
manifest_df = pd.DataFrame(crop_records)
manifest_csv = os.path.join(DRIVE_PROJECT, "tn5000_crops_manifest.csv")
manifest_df.to_csv(manifest_csv, index=False)
print("Saved crop manifest:", manifest_csv)

"""RESNET-54 REGULARIZED MODEL TRAINING"""

# ============================================================
# REGULARIZED RESNET-54 TRAINING - FIX OVERFITTING
# Run time: ~15-20 minutes on Tesla T4
# ============================================================

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models.resnet import ResNet, Bottleneck
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import pandas as pd
from PIL import Image
import numpy as np
import time
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# Dataset Class
# ============================================================
class UltrasoundDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.data = dataframe.reset_index(drop=True)
        self.transform = transform

        if self.data['label'].dtype == 'O':
            label_map = {'benign': 0, 'malignant': 1, 0: 0, 1: 1}
            self.data['label'] = self.data['label'].map(label_map)

        print(f"Dataset: {len(self.data)} samples | Labels: {dict(self.data['label'].value_counts())}")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]
        img_path = None
        if 'out_path' in row and pd.notna(row['out_path']):
            img_path = row['out_path']
        if img_path is None or not os.path.exists(img_path):
            if 'crop_name' in row:
                img_path = row['crop_name']

        try:
            img = Image.open(img_path).convert("RGB")
        except Exception as e:
            print(f"Error loading {img_path}: {e}")
            img = Image.new('RGB', (224, 224), color='white')

        label = torch.tensor(int(row['label']), dtype=torch.long)
        if self.transform:
            img = self.transform(img)
        return img, label

# ============================================================
# ResNet-54 with Dropout (Anti-Overfitting)
# ============================================================
class CustomResNetWithDropout(ResNet):
    def __init__(self, layers, num_classes=2, dropout_p=0.4, pretrained=True):
        super().__init__(block=Bottleneck, layers=layers, num_classes=1000)

        if pretrained:
            try:
                state_dict = torch.hub.load_state_dict_from_url(
                    'https://download.pytorch.org/models/resnet50-0676ba61.pth',
                    progress=True
                )
                del state_dict['fc.weight']
                del state_dict['fc.bias']
                self.load_state_dict(state_dict, strict=False)
                print(f"✓ Loaded pretrained weights")
            except Exception as e:
                print(f"⚠ Could not load pretrained weights: {e}")

        # Add dropout before final layer
        num_features = self.fc.in_features
        self.fc = nn.Sequential(
            nn.Dropout(p=dropout_p),
            nn.Linear(num_features, num_classes)
        )

def resnet54_v2_regularized(num_classes=2, dropout_p=0.4, pretrained=True):
    return CustomResNetWithDropout([3, 5, 6, 3], num_classes, dropout_p, pretrained)

# ============================================================
# Training Function
# ============================================================
def train_model_regularized(model, train_loader, val_loader, device, config):
    criterion = nn.CrossEntropyLoss(label_smoothing=config['label_smoothing'])

    optimizer = optim.AdamW(
        model.parameters(),
        lr=config['lr'],
        weight_decay=config['weight_decay']
    )

    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config['epochs'])

    model.to(device)
    best_val_acc = 0.0
    best_model_state = None
    patience = 5
    patience_counter = 0

    scaler = torch.cuda.amp.GradScaler()

    print("\n" + "="*80)
    print("TRAINING WITH REGULARIZATION")
    print("="*80)

    start_time = time.time()

    for epoch in range(config['epochs']):
        # Training
        model.train()
        train_loss, train_preds, train_targets = 0, [], []

        for imgs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{config['epochs']}", leave=False):
            imgs, labels = imgs.to(device, non_blocking=True), labels.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with torch.cuda.amp.autocast():
                outputs = model(imgs)
                loss = criterion(outputs, labels)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            train_loss += loss.item()
            train_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
            train_targets.extend(labels.cpu().numpy())

        train_acc = accuracy_score(train_targets, train_preds)
        train_f1 = f1_score(train_targets, train_preds, zero_division=0)

        # Validation
        model.eval()
        val_preds, val_targets, val_probs = [], [], []

        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs, labels = imgs.to(device, non_blocking=True), labels.to(device, non_blocking=True)

                with torch.cuda.amp.autocast():
                    outputs = model(imgs)

                probs = torch.softmax(outputs, dim=1)
                val_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
                val_targets.extend(labels.cpu().numpy())
                val_probs.extend(probs[:, 1].cpu().numpy())

        val_acc = accuracy_score(val_targets, val_preds)
        val_f1 = f1_score(val_targets, val_preds, zero_division=0)
        val_auc = roc_auc_score(val_targets, val_probs) if len(set(val_targets)) > 1 else 0.0

        # Calculate gap (overfitting indicator)
        gap = train_acc - val_acc

        print(f"E{epoch+1}: Train={train_acc:.3f} Val={val_acc:.3f} Gap={gap:.3f} | F1={val_f1:.3f} AUC={val_auc:.3f}", end="")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_model_state = model.state_dict().copy()
            patience_counter = 0
            print(f" ★ BEST")
        else:
            patience_counter += 1
            print()

        if patience_counter >= patience:
            print(f"\n⚠ Early stopping at epoch {epoch+1}")
            break

        scheduler.step()

    elapsed = time.time() - start_time
    print(f"\n⏱️  Training time: {elapsed/60:.1f} min")

    if best_model_state:
        model.load_state_dict(best_model_state)

    return model, best_val_acc

# ============================================================
# MAIN SCRIPT
# ============================================================
print("="*80)
print("RESNET-54 WITH REGULARIZATION - REDUCE OVERFITTING")
print("="*80)

MANIFEST_CSV = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/tn5000_crops_manifest.csv"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Regularization configuration
config = {
    'batch_size': 64,
    'epochs': 25,
    'lr': 8e-5,
    'weight_decay': 3e-4,  # 3x stronger than before
    'dropout': 0.4,
    'label_smoothing': 0.1,
    'img_size': 224
}

print(f"\n🔧 REGULARIZATION TECHNIQUES APPLIED:")
print(f"   ✓ Dropout: {config['dropout']} (was 0)")
print(f"   ✓ Weight Decay: {config['weight_decay']} (was 1e-4)")
print(f"   ✓ Label Smoothing: {config['label_smoothing']} (was 0)")
print(f"   ✓ Early Stopping: patience=5 (was 7)")
print(f"   ✓ Stronger Data Augmentation")
print(f"   ✓ Lower Learning Rate: {config['lr']}")

print(f"\n🎮 Device: {DEVICE}")
if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")

# Load data
print(f"\n📁 Loading data...")
full_data = pd.read_csv(MANIFEST_CSV)
train_data = full_data[full_data['split'] == 'train'].copy()
val_data = full_data[full_data['split'] == 'val'].copy()

print(f"   Train: {len(train_data)} samples")
print(f"   Val: {len(val_data)} samples")

# STRONGER data augmentation
train_tfms = transforms.Compose([
    transforms.Resize((config['img_size'], config['img_size'])),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(20),
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),
    transforms.ColorJitter(brightness=0.3, contrast=0.3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_tfms = transforms.Compose([
    transforms.Resize((config['img_size'], config['img_size'])),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

train_dataset = UltrasoundDataset(train_data, transform=train_tfms)
val_dataset = UltrasoundDataset(val_data, transform=val_tfms)

train_loader = DataLoader(
    train_dataset,
    batch_size=config['batch_size'],
    shuffle=True,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)
val_loader = DataLoader(
    val_dataset,
    batch_size=config['batch_size'] * 2,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)

# Build model
print(f"\n🏗️  Building ResNet-54 with regularization...")
model = resnet54_v2_regularized(
    num_classes=2,
    dropout_p=config['dropout'],
    pretrained=True
)

# Train
print(f"\n🚀 Starting training...")
trained_model, best_val_acc = train_model_regularized(
    model, train_loader, val_loader, DEVICE, config
)

# Save
save_name = f"resnet54_v2_REGULARIZED_acc{best_val_acc:.4f}.pth"
save_path = "/content/drive/MyDrive/FDL_Thyroid_Disease/Models/" + save_name
torch.save(trained_model.state_dict(), save_path)

print(f"\n" + "="*80)
print("TRAINING COMPLETE!")
print("="*80)
print(f"\n💾 Saved: {save_path}")
print(f"📊 Best Validation Accuracy: {best_val_acc:.4f} ({best_val_acc*100:.2f}%)")
print(f"\n✅ Next Step: Test this model using the testing script!")
print(f"   Expected: Test accuracy closer to validation (less overfitting)")

"""RESNET MODEL TRAINING - UNREGULARIZED"""

# ============================================================
# train_all_resnet_variants.py
# Train ResNet 54, 58, 60 with ALL possible block combinations
# ============================================================

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models.resnet import ResNet, Bottleneck
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix
import pandas as pd
from PIL import Image
import numpy as np
import warnings
import time
warnings.filterwarnings('ignore')

# ============================================================
# Dataset Class
# ============================================================
class UltrasoundDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.data = dataframe.reset_index(drop=True)
        self.transform = transform

        if self.data['label'].dtype == 'O':
            label_map = {'benign': 0, 'malignant': 1, 0: 0, 1: 1}
            self.data['label'] = self.data['label'].map(label_map)

        print(f"Dataset: {len(self.data)} samples | Labels: {dict(self.data['label'].value_counts())}")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]

        img_path = None
        if 'out_path' in row and pd.notna(row['out_path']):
            img_path = row['out_path']

        if img_path is None or not os.path.exists(img_path):
            if 'crop_name' in row:
                img_path = row['crop_name']

        try:
            img = Image.open(img_path).convert("RGB")
        except Exception as e:
            print(f"Error loading {img_path}: {e}")
            img = Image.new('RGB', (224, 224), color='white')

        label = torch.tensor(int(row['label']), dtype=torch.long)

        if self.transform:
            img = self.transform(img)

        return img, label

# ============================================================
# Custom ResNet Definitions - ALL VARIANTS
# ============================================================
class CustomResNet(ResNet):
    def __init__(self, layers, num_classes=2, pretrained=True):
        super().__init__(block=Bottleneck, layers=layers, num_classes=1000)

        if pretrained:
            try:
                state_dict = torch.hub.load_state_dict_from_url(
                    'https://download.pytorch.org/models/resnet50-0676ba61.pth',
                    progress=True
                )
                del state_dict['fc.weight']
                del state_dict['fc.bias']
                self.load_state_dict(state_dict, strict=False)
                print(f"✓ Loaded pretrained weights")
            except Exception as e:
                print(f"⚠ Could not load pretrained weights: {e}")

        num_features = self.fc.in_features
        self.fc = nn.Linear(num_features, num_classes)

# ============================================================
# ALL POSSIBLE RESNET ARCHITECTURES
# Format: [stage1_blocks, stage2_blocks, stage3_blocks, stage4_blocks]
# Total layers = (sum(blocks) * 3 + 2) for Bottleneck
# ============================================================

# ResNet-54 variants (total 54 layers)
def resnet54_v1(num_classes=2, pretrained=True): return CustomResNet([3,4,7,3], num_classes, pretrained)  # Standard
def resnet54_v2(num_classes=2, pretrained=True): return CustomResNet([3,5,6,3], num_classes, pretrained)
def resnet54_v3(num_classes=2, pretrained=True): return CustomResNet([3,6,5,3], num_classes, pretrained)
def resnet54_v4(num_classes=2, pretrained=True): return CustomResNet([4,4,6,3], num_classes, pretrained)
def resnet54_v5(num_classes=2, pretrained=True): return CustomResNet([3,4,6,4], num_classes, pretrained)

# ResNet-57 variants (total 57 layers)
def resnet57_v1(num_classes=2, pretrained=True): return CustomResNet([3,5,7,3], num_classes, pretrained)  # Balanced
def resnet57_v2(num_classes=2, pretrained=True): return CustomResNet([3,4,8,3], num_classes, pretrained)
def resnet57_v3(num_classes=2, pretrained=True): return CustomResNet([4,5,6,3], num_classes, pretrained)
def resnet57_v4(num_classes=2, pretrained=True): return CustomResNet([3,6,6,3], num_classes, pretrained)
def resnet57_v5(num_classes=2, pretrained=True): return CustomResNet([4,4,7,3], num_classes, pretrained)

# ResNet-58 variants (total 58 layers)
def resnet58_v1(num_classes=2, pretrained=True): return CustomResNet([3,4,8,3], num_classes, pretrained)  # Standard
def resnet58_v2(num_classes=2, pretrained=True): return CustomResNet([3,5,7,3], num_classes, pretrained)
def resnet58_v3(num_classes=2, pretrained=True): return CustomResNet([3,6,6,3], num_classes, pretrained)
def resnet58_v4(num_classes=2, pretrained=True): return CustomResNet([4,5,6,3], num_classes, pretrained)
def resnet58_v5(num_classes=2, pretrained=True): return CustomResNet([4,4,7,3], num_classes, pretrained)

# ResNet-60 variants (total 60 layers)
def resnet60_v1(num_classes=2, pretrained=True): return CustomResNet([3,4,9,3], num_classes, pretrained)  # Standard
def resnet60_v2(num_classes=2, pretrained=True): return CustomResNet([3,5,8,3], num_classes, pretrained)
def resnet60_v3(num_classes=2, pretrained=True): return CustomResNet([3,6,7,3], num_classes, pretrained)
def resnet60_v4(num_classes=2, pretrained=True): return CustomResNet([4,5,7,3], num_classes, pretrained)
def resnet60_v5(num_classes=2, pretrained=True): return CustomResNet([4,4,8,3], num_classes, pretrained)
def resnet60_v6(num_classes=2, pretrained=True): return CustomResNet([3,7,6,3], num_classes, pretrained)

# ============================================================
# Fast Training Function
# ============================================================
def train_model(model, train_loader, val_loader, device, config):
    criterion = nn.CrossEntropyLoss()

    if config['optimizer'] == 'adamw':
        optimizer = optim.AdamW(
            model.parameters(),
            lr=config['lr'],
            weight_decay=config['weight_decay']
        )
    else:
        optimizer = optim.SGD(
            model.parameters(),
            lr=config['lr'],
            momentum=0.9,
            weight_decay=config['weight_decay']
        )

    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config['epochs'])

    model.to(device)
    best_val_acc = 0.0
    best_val_f1 = 0.0
    best_model_state = None
    patience = 7
    patience_counter = 0

    scaler = torch.cuda.amp.GradScaler() if device == 'cuda' else None
    use_amp = device == 'cuda'

    start_time = time.time()

    for epoch in range(config['epochs']):
        # Training
        model.train()
        train_loss, train_preds, train_targets = 0, [], []

        for imgs, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{config['epochs']}", leave=False):
            imgs, labels = imgs.to(device, non_blocking=True), labels.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            if use_amp:
                with torch.cuda.amp.autocast():
                    outputs = model(imgs)
                    loss = criterion(outputs, labels)
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                outputs = model(imgs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

            train_loss += loss.item()
            train_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
            train_targets.extend(labels.cpu().numpy())

        train_acc = accuracy_score(train_targets, train_preds)
        train_f1 = f1_score(train_targets, train_preds, zero_division=0)

        # Validation
        model.eval()
        val_preds, val_targets, val_probs = [], [], []

        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs, labels = imgs.to(device, non_blocking=True), labels.to(device, non_blocking=True)

                if use_amp:
                    with torch.cuda.amp.autocast():
                        outputs = model(imgs)
                else:
                    outputs = model(imgs)

                probs = torch.softmax(outputs, dim=1)
                val_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
                val_targets.extend(labels.cpu().numpy())
                val_probs.extend(probs[:, 1].cpu().numpy())

        val_acc = accuracy_score(val_targets, val_preds)
        val_f1 = f1_score(val_targets, val_preds, zero_division=0)
        val_auc = roc_auc_score(val_targets, val_probs) if len(set(val_targets)) > 1 else 0.0

        print(f"E{epoch+1}: Train Acc={train_acc:.3f} F1={train_f1:.3f} | Val Acc={val_acc:.3f} F1={val_f1:.3f} AUC={val_auc:.3f}", end="")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_val_f1 = val_f1
            best_model_state = model.state_dict().copy()
            patience_counter = 0
            print(f" ★")
        else:
            patience_counter += 1
            print()

        if patience_counter >= patience:
            print(f"⚠ Early stopping at epoch {epoch+1}")
            break

        scheduler.step()

    elapsed = time.time() - start_time
    print(f"⏱️  Training time: {elapsed/60:.1f} min")

    if best_model_state:
        model.load_state_dict(best_model_state)

    return model, best_val_acc, best_val_f1

# ============================================================
# Main Script
# ============================================================
if __name__ == "__main__":

    # ========================================
    # CONFIGURATION
    # ========================================
    MANIFEST_CSV = "/content/drive/MyDrive/FDL_Thyroid_Disease/Project/tn5000_crops_manifest.csv"

    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"🖥️  Device: {DEVICE}")
    if torch.cuda.is_available():
        print(f"🎮 GPU: {torch.cuda.get_device_name(0)}")
    print()

    # ========================================
    # BEST CONFIGURATIONS (based on your results)
    # ========================================
    configs = [
        # Best performing configs from ResNet-50 testing
        {
            'name': 'fast',  # Your best: 93.21% in 5.4 min
            'batch_size': 96,
            'epochs': 25,
            'lr': 1.5e-4,
            'weight_decay': 1e-4,
            'optimizer': 'adamw',
            'img_size': 224
        },
        {
            'name': 'baseline',  # Proven: 92.22%
            'batch_size': 64,
            'epochs': 25,
            'lr': 1e-4,
            'weight_decay': 1e-4,
            'optimizer': 'adamw',
            'img_size': 224
        },
        {
            'name': 'stable',  # Conservative approach
            'batch_size': 64,
            'epochs': 25,
            'lr': 8e-5,
            'weight_decay': 1e-4,
            'optimizer': 'adamw',
            'img_size': 224
        },
    ]

    # ========================================
    # ALL RESNET VARIANTS TO TEST
    # ========================================
    model_variants = {
        # ResNet-54 (5 variants)
        "resnet54_v1_[3,4,7,3]": resnet54_v1,
        "resnet54_v2_[3,5,6,3]": resnet54_v2,
        "resnet54_v3_[3,6,5,3]": resnet54_v3,
        "resnet54_v4_[4,4,6,3]": resnet54_v4,
        "resnet54_v5_[3,4,6,4]": resnet54_v5,

        # ResNet-57 (5 variants)
        "resnet57_v1_[3,5,7,3]": resnet57_v1,
        "resnet57_v2_[3,4,8,3]": resnet57_v2,
        "resnet57_v3_[4,5,6,3]": resnet57_v3,
        "resnet57_v4_[3,6,6,3]": resnet57_v4,
        "resnet57_v5_[4,4,7,3]": resnet57_v5,

        # ResNet-58 (5 variants)
        "resnet58_v1_[3,4,8,3]": resnet58_v1,
        "resnet58_v2_[3,5,7,3]": resnet58_v2,
        "resnet58_v3_[3,6,6,3]": resnet58_v3,
        "resnet58_v4_[4,5,6,3]": resnet58_v4,
        "resnet58_v5_[4,4,7,3]": resnet58_v5,

        # ResNet-60 (6 variants)
        "resnet60_v1_[3,4,9,3]": resnet60_v1,
        "resnet60_v2_[3,5,8,3]": resnet60_v2,
        "resnet60_v3_[3,6,7,3]": resnet60_v3,
        "resnet60_v4_[4,5,7,3]": resnet60_v4,
        "resnet60_v5_[4,4,8,3]": resnet60_v5,
        "resnet60_v6_[3,7,6,3]": resnet60_v6,
    }

    print(f"🔢 Total experiments: {len(model_variants)} models × {len(configs)} configs = {len(model_variants) * len(configs)} total\n")

    # ========================================
    # LOAD DATA
    # ========================================
    print(f"📁 Loading data from CSV...")
    full_data = pd.read_csv(MANIFEST_CSV)

    train_data = full_data[full_data['split'] == 'train'].copy()
    val_data = full_data[full_data['split'] == 'val'].copy()
    test_data = full_data[full_data['split'] == 'test'].copy()

    print(f"Train: {len(train_data)} | Val: {len(val_data)} | Test: {len(test_data)}\n")

    # ========================================
    # TRAINING LOOP
    # ========================================
    all_results = []
    experiment_num = 0
    total_experiments = len(model_variants) * len(configs)

    for model_name, model_fn in model_variants.items():
        print(f"\n{'='*80}")
        print(f"🚀 MODEL: {model_name}")
        print(f"{'='*80}\n")

        for config in configs:
            experiment_num += 1
            print(f"📊 Experiment {experiment_num}/{total_experiments} | Config: {config['name']} | Batch={config['batch_size']} | LR={config['lr']}")

            # Transforms
            train_tfms = transforms.Compose([
                transforms.Resize((config['img_size'], config['img_size'])),
                transforms.RandomHorizontalFlip(p=0.5),
                transforms.RandomVerticalFlip(p=0.3),
                transforms.RandomRotation(15),
                transforms.ColorJitter(brightness=0.2, contrast=0.2),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])

            val_tfms = transforms.Compose([
                transforms.Resize((config['img_size'], config['img_size'])),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])

            # Datasets
            train_dataset = UltrasoundDataset(train_data, transform=train_tfms)
            val_dataset = UltrasoundDataset(val_data, transform=val_tfms)

            # Loaders
            train_loader = DataLoader(
                train_dataset,
                batch_size=config['batch_size'],
                shuffle=True,
                num_workers=4,
                pin_memory=True,
                persistent_workers=True,
                prefetch_factor=2
            )
            val_loader = DataLoader(
                val_dataset,
                batch_size=config['batch_size'] * 2,
                shuffle=False,
                num_workers=4,
                pin_memory=True,
                persistent_workers=True,
                prefetch_factor=2
            )

            # Initialize model
            model = model_fn(num_classes=2, pretrained=True)

            # Train
            trained_model, best_acc, best_f1 = train_model(
                model, train_loader, val_loader, DEVICE, config
            )

            # Save model
            save_name = f"{model_name}_{config['name']}_acc{best_acc:.4f}.pth"
            torch.save(trained_model.state_dict(), save_name)
            print(f"💾 Saved: {save_name}\n")

            # Store results
            all_results.append({
                'model': model_name,
                'config': config['name'],
                'val_acc': best_acc,
                'val_f1': best_f1,
                'batch_size': config['batch_size'],
                'lr': config['lr'],
                'img_size': config['img_size'],
                'saved_as': save_name
            })

            # Cleanup
            del model, trained_model, train_loader, val_loader, train_dataset, val_dataset
            torch.cuda.empty_cache()

    # ========================================
    # RESULTS SUMMARY
    # ========================================
    print(f"\n\n{'='*80}")
    print("📈 FINAL RESULTS - ALL RESNET VARIANTS")
    print(f"{'='*80}\n")

    results_df = pd.DataFrame(all_results)
    results_df = results_df.sort_values('val_acc', ascending=False)

    print(results_df[['model', 'config', 'val_acc', 'val_f1', 'lr', 'batch_size']].to_string(index=False))

    results_df.to_csv('all_resnet_variants_results.csv', index=False)
    print(f"\n✅ Results saved to: all_resnet_variants_results.csv")

    # Top 10 models
    print(f"\n{'='*80}")
    print("🏆 TOP 10 BEST MODELS")
    print(f"{'='*80}")
    for i in range(min(10, len(results_df))):
        row = results_df.iloc[i]
        print(f"{i+1}. {row['model']} ({row['config']})")
        print(f"   Acc: {row['val_acc']:.4f} | F1: {row['val_f1']:.4f}")
        print(f"   File: {row['saved_as']}\n")

    # ========================================
    # TEST BEST MODEL
    # ========================================
    print(f"{'='*80}")
    print("🧪 TESTING BEST MODEL ON TEST SET")
    print(f"{'='*80}\n")

    best_row = results_df.iloc[0]
    print(f"Best Model: {best_row['model']} ({best_row['config']})")
    print(f"Validation Accuracy: {best_row['val_acc']:.4f}")
    print(f"Loading: {best_row['saved_as']}\n")

    # Extract model name and load
    model_key = best_row['model']
    best_model = model_variants[model_key](num_classes=2, pretrained=False)
    best_model.load_state_dict(torch.load(best_row['saved_as']))
    best_model.to(DEVICE)
    best_model.eval()

    # Test dataset
    test_tfms = transforms.Compose([
        transforms.Resize((int(best_row['img_size']), int(best_row['img_size']))),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    test_dataset = UltrasoundDataset(test_data, transform=test_tfms)
    test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False, num_workers=4, pin_memory=True)

    # Evaluate
    test_preds, test_targets, test_probs = [], [], []

    with torch.no_grad():
        for imgs, labels in tqdm(test_loader, desc="Testing"):
            imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)

            with torch.cuda.amp.autocast():
                outputs = best_model(imgs)
            probs = torch.softmax(outputs, dim=1)

            test_preds.extend(torch.argmax(outputs, 1).cpu().numpy())
            test_targets.extend(labels.cpu().numpy())
            test_probs.extend(probs[:, 1].cpu().numpy())

    test_acc = accuracy_score(test_targets, test_preds)
    test_f1 = f1_score(test_targets, test_preds)
    test_auc = roc_auc_score(test_targets, test_probs)
    test_cm = confusion_matrix(test_targets, test_preds)

    print(f"\n{'='*80}")
    print(f"🎯 TEST SET RESULTS")
    print(f"{'='*80}")
    print(f"Accuracy:  {test_acc:.4f}")
    print(f"F1 Score:  {test_f1:.4f}")
    print(f"AUC-ROC:   {test_auc:.4f}")
    print(f"\nConfusion Matrix:")
    print(test_cm)
    print(f"{'='*80}\n")

    # Final summary
    final_results = {
        'best_model': best_row['model'],
        'best_config': best_row['config'],
        'validation_accuracy': float(best_row['val_acc']),
        'validation_f1': float(best_row['val_f1']),
        'test_accuracy': float(test_acc),
        'test_f1': float(test_f1),
        'test_auc': float(test_auc),
        'saved_as': best_row['saved_as'],
        'all_results': results_df.to_dict('records')
    }

    import json
    with open('final_all_variants_results.json', 'w') as f:
        json.dump(final_results, f, indent=4)

    print("✅ Final results saved to: final_all_variants_results.json")
    print(f"\n🏆 WINNER: {best_row['model']} ({best_row['config']})")
    print(f"📊 Test Accuracy: {test_acc:.4f}")
    print(f"💾 Model file: {best_row['saved_as']}\n")

    # Summary statistics by architecture
    print(f"{'='*80}")
    print("📊 SUMMARY BY ARCHITECTURE")
    print(f"{'='*80}")
    for arch in ['resnet54', 'resnet57', 'resnet58', 'resnet60']:
        arch_results = results_df[results_df['model'].str.contains(arch)]
        if len(arch_results) > 0:
            best_variant = arch_results.iloc[0]
            avg_acc = arch_results['val_acc'].mean()
            print(f"\n{arch.upper()}:")
            print(f"  Best variant: {best_variant['model']}")
            print(f"  Best accuracy: {best_variant['val_acc']:.4f}")
            print(f"  Average accuracy: {avg_acc:.4f}")
            print(f"  Tested: {len(arch_results)} combinations")